# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ conntrack_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - conntrack
    - conntrack-install-dependencies

- name: load kernel modules
  community.general.modprobe:
    name: "{{ item.name }}"
  with_items: "{{ conntrack_kernel_modules }}"
  tags:
    - configuration
    - conntrack
    - conntrack-load-kernel-modules

- name: check kernel module parameters
  ansible.builtin.shell: >
    cat /sys/module/{{ item.0.name }}/parameters/{{ item.1.name }}
  register: _check_kernel_module_parameters
  failed_when: false
  changed_when: false
  check_mode: false
  with_subelements:
    - "{{ conntrack_kernel_modules | selectattr('params', 'defined') | list }}"
    - params
  tags:
    - configuration
    - conntrack
    - conntrack-check-kernel-module-parameters

- name: apply kernel module parameters
  ansible.builtin.copy:
    content: "{{ item.item.1.value }}"
    dest: "/sys/module/{{ item.item.0.name }}/parameters/{{ item.item.1.name }}"
    mode: preserve
    unsafe_writes: true
  changed_when: item.stdout != item.item.1.value | string
  with_items: "{{ _check_kernel_module_parameters.results | default([]) }}"
  tags:
    - configuration
    - conntrack
    - conntrack-apply-kernel-module-parameters

- name: save kernel modules
  ansible.builtin.lineinfile:
    dest: /etc/modules
    line: "{{ item.name }}"
  with_items: "{{ conntrack_kernel_modules }}"
  tags:
    - configuration
    - conntrack
    - conntrack-save-kernel-modules

- name: save kernel module parameters
  ansible.builtin.template:
    src: etc/modprobe.d/config.conf.j2
    dest: "/etc/modprobe.d/{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ conntrack_kernel_modules }}"
  tags:
    - configuration
    - conntrack
    - conntrack-save-kernel-module-parameters

- name: set sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | string }}"
    reload: true
    state: present
  with_items: "{{ conntrack_sysctl_settings }}"
  tags:
    - configuration
    - conntrack
    - conntrack-set-sysctl-settings
